apiVersion: v1
kind: Service
metadata:
    name: node-red-service
    labels:
        app: node-red-service
    annotations:
        dev.okteto.com/auto-ingress: "true"
spec:
    type: ClusterIP
    ports:
      - port: 80
        protocol: TCP
        targetPort: 1880
    selector:
        app: node-red
