apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-red
spec:
  replicas: 1
  selector:
    matchLabels:
      run: node-red
  template:
    metadata:
      labels:
        run: node-red
    spec:
      containers:
      - name: node-red
        image: axcap/smarthouserepo:smartnora
        imagePullPolicy: Always
